import dynamic from "next/dynamic";
import Head from "next/head";

const View = dynamic(() => import("../components/view").then((m) => m.View), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <View />
      </main>
    </>
  );
}
